// emoji 名称映射到实际的 emoji 字符
export const emojiMap: Record<string, string> = {
  exploding_head: "🤯",
  robot: "🤖",
  thinking: "🤔",
  bulb: "💡",
  rocket: "🚀",
  star: "⭐",
  heart: "❤️",
  fire: "🔥",
  thumbs_up: "👍",
  sunglasses: "😎",
  nerd: "🤓",
  smile: "😊",
  wink: "😉",
  laugh: "😂",
  money: "💰",
  chart: "📊",
  book: "📚",
  computer: "💻",
  wrench: "🔧",
  gear: "⚙️",
  magic: "✨",
  rainbow: "🌈",
  cloud: "☁️",
  sun: "☀️",
  moon: "🌙",
  earth: "🌍",
  puzzle: "🧩",
  light_bulb: "💡",
  warning: "⚠️",
  question: "❓",
  check: "✅",
  cross: "❌",
  lock: "🔒",
  key: "🔑",
  search: "🔍",
  link: "🔗",
  clock: "🕒",
  calendar: "📅",
  phone: "📱",
  mail: "📧",
  chat: "💬",
  music: "🎵",
  video: "🎬",
  camera: "📷",
  microphone: "🎤",
  speaker: "🔊",
  bell: "🔔",
  gift: "🎁",
  trophy: "🏆",
  medal: "🏅",
  flag: "🚩",
  target: "🎯",
  hammer: "🔨",
  tools: "🛠️",
  pill: "💊",
  syringe: "💉",
  dna: "🧬",
  microscope: "🔬",
  telescope: "🔭",
  satellite: "📡",
  world: "🌎",
  compass: "🧭",
  map: "🗺️",
  location: "📍",
  building: "🏢",
  house: "🏠",
  school: "🏫",
  hospital: "🏥",
  bank: "🏦",
  factory: "🏭",
  construction: "🚧",
  truck: "🚚",
  car: "🚗",
  airplane: "✈️",
  ship: "🚢",
  train: "🚆",
  bicycle: "🚲",
  fuel: "⛽",
  atom: "⚛️",
  infinity: "♾️",
  recycle: "♻️",
  trident: "🔱",
  anchor: "⚓",
  wheel: "🛞",
  hammer_and_wrench: "🛠️",
  shield: "🛡️",
  skull: "💀",
  ghost: "👻",
  alien: "👽",
  monster: "👾",
  dragon: "🐉",
  dinosaur: "🦖",
  unicorn: "🦄",
  cat: "🐱",
  dog: "🐶",
  fox: "🦊",
  panda: "🐼",
  penguin: "🐧",
  owl: "🦉",
  butterfly: "🦋",
  flower: "🌸",
  four_leaf_clover: "🍀",
  crystal_ball: "🔮",
  joystick: "🕹️",
  game: "🎮",
  dice: "🎲",
  chess: "♟️",
  dart: "🎯",
  bowling: "🎳",
  football: "⚽",
  basketball: "🏀",
  baseball: "⚾",
  tennis: "🎾",
  volleyball: "🏐",
  rugby: "🏉",
  badminton: "🏸",
  ping_pong: "🏓",
  boxing_glove: "🥊",
  martial_arts: "🥋",
  goal: "🥅",
  fishing: "🎣",
  running: "🏃",
  swimming: "🏊",
  surfing: "🏄",
  skiing: "⛷️",
  snowboarding: "🏂",
  golfing: "🏌️",
  climbing: "🧗",
  biking: "🚴",
  military_medal: "🎖️",
  first_place: "🥇",
  second_place: "🥈",
  third_place: "🥉",
};

/**
 * 将 emoji 名称转换为实际的 emoji 字符
 * @param emojiName emoji 名称
 * @returns 实际的 emoji 字符
 */
export const getEmojiFromName = (emojiName: string): string => {
  // 如果已经是 emoji 字符，直接返回
  if (emojiName.length <= 2 || /\p{Emoji}/u.test(emojiName)) {
    return emojiName;
  }

  // 从映射中查找
  return emojiMap[emojiName] || "🤖"; // 默认返回机器人 emoji
};
